name: Auto Preprocessing

on:
  push:
    branches:
      - main

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Pandas
        run: pip install pandas

      - name: Run Preprocessing
        run: python automate_Elida-Silaban.py
